site_name: Demo Documentation
site_url: https://rgeerkens.github.io/Documentation/
repo_url: https://github.com/rgeerkens/Documentation
repo_name: Documentation Github

theme:
    name: material
    palette:
        primary: blue
        accent: white

nav:
    - Home: index.md
    - About : about.md
    - Other:
      - License: licenses.md
      - Release Notes : release-notes.md
    - Report Issue: https://github.com/rgeerkens/Documentation/issues/new
    - Bug Tracker: bugs.md
