site_name: Demo Documentation
site_url: https://rgeerkens.github.io/Documentation/
repo_url: https://github.com/rgeerkens/Documentation
repo_name: Documentation Github
edit_uri: ""

theme:
    name: material
    palette:
        primary: blue
        accent: white
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.expand
      - navigation.indexes
      - toc.follow
      - navigation.top
    icon:
      tag:
        html: fontawesome/brands/html5
        js: fontawesome/brands/js
        css:  fontawesome/brands/css3
      repo: fontawesome/brands/github

extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  generator: false
  version:
    provider: mike
    default: latest
    
plugins:
  - tags
  - search
  - external-markdown

markdown_extensions:
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs

nav:
    - Home: 
        - index.md
        - Other:
          - License: licenses.md
          - Release Notes : release-notes.md
        - Bug Tracker: bugs.md
        - Training (sync remote repo) : training/README.md
        - Bastion Demo (sync remote repo) : bastion-demo/README.md
        - Automatic Changelog : changelog.md
        - Demo Pdf: embed-pdf.md
        - Demo Word: embed-word.md
        - Demo Excel: embed-excel.md
        - Md Embed Demo: embed-md.md
        - Flows Demo: embed-flows.md
    - Packages : https://github.com/rgeerkens?tab=packages&repo_name=Documentation
    - About : about.md
    - Report Issue: https://github.com/rgeerkens/Documentation/issues/new/choose
