site_name: Demo Documentation
site_url: https://rgeerkens.github.io/Documentation/
#repo_url: https://github.com/rgeerkens/Documentation/tree/main/docs
repo_url: https://github.com/rgeerkens/Documentation
repo_name: Documentation Github
edit_uri: ""

theme:
    name: material
    palette:
        primary: blue
        accent: white
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs
      - navigation.expand
      - navigation.indexes
      - toc.follow
      - navigation.top
    icon:
      tag:
        html: fontawesome/brands/html5
        js: fontawesome/brands/js
        css:  fontawesome/brands/css3
      repo: fontawesome/brands/github

extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  generator: false
  version:
    provider: mike
    default: latest
    
plugins:
  - tags
  - search

markdown_extensions:
  - toc:
      permalink: true

nav:
    - Home: 
        - index.md
        - Other:
          - License: licenses.md
          - Release Notes : release-notes.md
        - Bug Tracker: bugs.md
        - Training (remote repo) : training/README.md

    - About : about.md
    - Report Issue: https://github.com/rgeerkens/Documentation/issues/new
