site_name: Demo Documentation
site_url: https://rgeerkens.github.io/Documentation/
repo_url: https://github.com/rgeerkens/Documentation
repo_name: Documentation Github

theme:
    name: material
    palette:
        primary: blue
        accent: white
    features:
      - navigation.instant
      - navigation.tracking
      - navigation.tabs

nav:
    - Home: 
        - Home: index.md
        - Other:
          - License: licenses.md
          - Release Notes : release-notes.md
        - Bug Tracker: bugs.md

    - About : about.md
    - Report Issue: https://github.com/rgeerkens/Documentation/issues/new
