name: Request Enhancement
description: Request our thoughts on your suggestion for a new feature.
labels: [enhancement, triage]

body:
  - type: markdown
    attributes:
      value: Please note we will close your enhancement request without comment if you do not fill out the checklist below and provide ALL the requested 
  - type: textarea
    attributes:
      label: Provide a detailed description of the proposed feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the motivation for the feature?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives to the feature have been considered?
    validations:
      required: true
  - type: markdown
    attributes:
      value: We will close this issue or ask you to create a pull-request if it's something the maintainers are not actively planning to work on.
