name: Build Site
on:
  #push:
  #  branches:
  #    - master 
  #    - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mike
      - run: pip install mkdocs-embed-external-markdown
      - run: pip install markdown-include
#      - run: mkdocs gh-deploy --force
      - run: git config user.name rgeerkens
      - run: git config user.email ronny.geerkens@telenet.be
      - run: git pull
      - run: mike deploy --push --update-aliases 3.0 latest
#      - run: mike set-default --push latest