name: Add bugs to bugs project

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/users/rgeerkens/projects/2
          github-token: ${{ secrets.ISSUES_TOKEN }}
          labeled: documentation, triage
          label-operator: OR