name: Auto Assign to Project(s)

on:
  issues:
    types: [created, labeled]
env:
  MY_GITHUB_TOKEN: ${{ secrets.ISSUES_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign triage issues to demo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'bi-issue')
      with:
        project: 'https://github.com/users/rgeerkens/projects/2'
        column_name: 'Test'