name: Assign Issues to Project(s)

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
  

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_demo_project:
    runs-on: ubuntu-latest
    name: Assign to Demo Documentation Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/rgeerkens/projects/2'

#    - name: Assign issues and pull requests with `bug` label to project 3
#      uses: srggrs/assign-one-project-github-action@1.2.1
#      if: |
#        contains(github.event.issue.labels.*.name, 'bug') ||
#        contains(github.event.pull_request.labels.*.name, 'bug')
#      with:
#        project: 'https://github.com/srggrs/assign-one-project-github-action/projects/3'
#        column_name: 'Labeled'