name: Changelog

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Create local changes
        run: |
          echo "# Release Notes" > docs/changelog.md
          echo "" >> docs/changelog.md
          echo "## Releases" >> docs/changelog.md
          git log --all --pretty=format:"- %ad | %s %d [%an] | %b" --date=short | grep -F "[release]" >> docs/changelog.md
          echo "" >> docs/changelog.md
          echo "## Bugfixes" >> docs/changelog.md
          git log --all --pretty=format:"- %ad | %s %d [%an] | %b" --date=short | grep -F "[bugfix]" >> docs/changelog.md
          echo "" >> docs/changelog.md
          echo "## Enhancements" >> docs/changelog.md
          git log --all --pretty=format:"- %ad | %s %d [%an] | %b" --date=short | grep -F "[enhancement]" >> docs/changelog.md
          git add docs/changelog.md
      - name: Commit files
        run: |
          git config --local user.email "ronny.geerkens@telenet.be"
          git config --local user.name "rgeerkens"
          git commit -am "Change Log Created / Updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
