name: Changelog

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with: 
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create local changes
        run: |
           echo ${{steps.build_changelog.outputs.changelog}} >> changelog.md
           cat changelog.md
#          git add changelog.md
#      - name: Commit files
#        run: |
#          git config --local user.email "ronny.geerkens@telenet.be"
#          git config --local user.name "rgeerkens"
#          git commit -am "Change Log Created / Updated"
#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: ${{ github.ref }}
#          echo ${{steps.build_changelog.outputs.changelog}} >> changelog.md
